-- Generated by install/set-theme.py from themes/mocha.toml — do not edit.
--
-- Theme: Catppuccin Mocha
--
-- Hyprland accepts colours as "rgb(rrggbb)" or "rgba(rrggbbaa)".
-- The `_a` variants are semi-transparent, for borders and shadows.

return {
  base      = "rgb(1e1e2e)",
  blue      = "rgb(89b4fa)",
  crust     = "rgb(11111b)",
  flamingo  = "rgb(f2cdcd)",
  green     = "rgb(a6e3a1)",
  lavender  = "rgb(b4befe)",
  mantle    = "rgb(181825)",
  maroon    = "rgb(eba0ac)",
  mauve     = "rgb(cba6f7)",
  overlay0  = "rgb(6c7086)",
  overlay1  = "rgb(7f849c)",
  overlay2  = "rgb(9399b2)",
  peach     = "rgb(fab387)",
  pink      = "rgb(f5c2e7)",
  red       = "rgb(f38ba8)",
  rosewater = "rgb(f5e0dc)",
  sapphire  = "rgb(74c7ec)",
  sky       = "rgb(89dceb)",
  subtext0  = "rgb(a6adc8)",
  subtext1  = "rgb(bac2de)",
  surface0  = "rgb(313244)",
  surface1  = "rgb(45475a)",
  surface2  = "rgb(585b70)",
  teal      = "rgb(94e2d5)",
  text      = "rgb(cdd6f4)",
  yellow    = "rgb(f9e2af)",

  -- Semantic roles — what a colour *means*, not what it is.
  accent    = "rgb(cba6f7)",
  accent_alt= "rgb(89b4fa)",
  info      = "rgb(f9e2af)",
  link      = "rgb(89b4fa)",
  success   = "rgb(a6e3a1)",
  urgent    = "rgb(f38ba8)",
  warning   = "rgb(fab387)",

  -- Semi-transparent, for gradients and shadows.
  accent_a  = "rgba(cba6f7ee)",
  accent2_a = "rgba(89b4faee)",
  surface_a = "rgba(45475aaa)",
  shadow    = "rgba(11111bee)",
}
