#!/usr/bin/env bash
# Theme the login screen.
#
#   ./install/sddm.sh              apply the current theme's SDDM theme
#   ./install/sddm.sh --dry-run    print what would be written, touch nothing
#   ./install/sddm.sh --show       print the current SDDM config and exit
#
# This is separate from set-theme.py, and from link.sh, for a reason worth
# understanding rather than working around.
#
# SDDM is not part of your session. It runs as the `sddm` system user, on its
# own VT, BEFORE you log in — so it cannot read ~/.config, it is not affected
# by `hyprctl reload`, and it does not see anything link.sh symlinks. Its
# config lives in /etc/sddm.conf.d/ and its themes in /usr/share/sddm/themes/,
# both root-owned. Every other file in this repo is written without a password;
# this one is not, which is why it is a separate script you run deliberately
# rather than a side effect of switching themes.
#
# Consequence: the login screen does NOT follow SUPER+ALT+T. Re-run this after
# switching themes if you want it to match.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

CONF_DIR="/etc/sddm.conf.d"
CONF="$CONF_DIR/10-hypersetup.conf"
THEME_ROOT="/usr/share/sddm/themes"

DRY_RUN=0
SHOW=0
for arg in "$@"; do
	case "$arg" in
	--dry-run) DRY_RUN=1 ;;
	--show) SHOW=1 ;;
	*)
		echo "unknown flag: $arg" >&2
		exit 1
		;;
	esac
done

die() {
	printf '\033[31mError:\033[0m %s\n' "$*" >&2
	exit 1
}
note() { printf '  %s\n' "$*"; }

if ((SHOW)); then
	echo "==> $CONF"
	if [[ -f $CONF ]]; then cat "$CONF"; else echo "  (not written yet)"; fi
	echo
	echo "==> installed themes in $THEME_ROOT"
	if [[ -d $THEME_ROOT ]]; then
		ls -1 "$THEME_ROOT" | sed 's/^/  /'
	else
		echo "  (no theme directory — is sddm installed?)"
	fi
	exit 0
fi

# --- which theme --------------------------------------------------------
# Read the same theme.env that scripts/theme.sh reads, so the login screen
# and the desktop cannot disagree about which theme is current.
ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/theme.env"
[[ -f $ENV_FILE ]] || die "$ENV_FILE not found — run ./install/set-theme.py <theme> first."

# shellcheck source=/dev/null
. "$ENV_FILE"

: "${SDDM_THEME_NAME:=}"
: "${THEME_LABEL:=unknown}"
[[ -n $SDDM_THEME_NAME ]] ||
	die "themes/${THEME_NAME:-?}.toml has no sddm_theme. Add one, then re-run."

THEME_DIR="$THEME_ROOT/$SDDM_THEME_NAME"
if [[ ! -d $THEME_DIR ]]; then
	# The package is named after the flavour only — one package ships all
	# fourteen accent variants. So catppuccin-mocha-mauve and
	# catppuccin-mocha-peach both come from catppuccin-sddm-theme-mocha.
	flavour="${SDDM_THEME_NAME#catppuccin-}" # mocha-mauve
	flavour="${flavour%%-*}"                 # mocha

	echo "The theme '$SDDM_THEME_NAME' is not installed. Install it with:" >&2
	echo >&2
	echo "    paru -S catppuccin-sddm-theme-$flavour" >&2
	echo >&2
	# A dry run is for reading the output, and refusing to print it on a
	# machine that hasn't installed the theme yet defeats the point.
	((DRY_RUN)) || exit 1
	echo "Continuing anyway: --dry-run writes nothing." >&2
	echo >&2
fi

# --- what we're going to write -----------------------------------------
# Font and cursor come from the desktop config so the login screen is not the
# one place with a different cursor. A stock X11 cursor over a themed greeter
# is the single most obvious "unthemed" tell.
CURSOR="$(sed -n 's/^export XCURSOR_THEME=//p' config/uwsm/env | head -1)"
CURSOR="${CURSOR:-Bibata-Modern-Classic}"
CURSOR_SIZE="$(sed -n 's/^export XCURSOR_SIZE=//p' config/uwsm/env | head -1)"
CURSOR_SIZE="${CURSOR_SIZE:-24}"

read -r -d '' MAIN_CONF <<EOF
# Generated by install/sddm.sh — do not edit; edit the repo and re-run.
#
# Drop-in, so it overrides /etc/sddm.conf without replacing it. Files in
# /etc/sddm.conf.d are read in alphabetical order; 10- puts this after
# anything a package ships as 00-.

[Theme]
Current=$SDDM_THEME_NAME
# Matching the desktop. Inter for UI text, Bibata for the pointer.
Font=Inter
CursorTheme=$CURSOR
CursorSize=$CURSOR_SIZE
# One user on this machine, so the avatar grid is a row of one placeholder.
EnableAvatars=false

[General]
# Qt's automatic high-DPI scaling is already on by default for both display
# servers; left alone deliberately. If the greeter comes up too small on the
# 2560x1600 panel, the knob is GreeterEnvironment=QT_FONT_DPI=144 here rather
# than a font size in the theme.
#
# DisplayServer is left at its default of x11. SDDM's own config source calls
# Wayland support experimental, and it needs a separate compositor
# (Wayland.CompositorCommand defaults to \`weston --shell=kiosk\`, which is not
# installed). Not worth risking the login screen for.
Numlock=on

[Users]
HideShells=/usr/bin/nologin,/sbin/nologin,/bin/false
EOF

# theme.conf.user, NOT theme.conf.
#
# SDDM reads "<theme.conf path>.user" and lets its non-empty keys override the
# theme's own — see ThemeConfig::setTo in sddm's source. That matters because
# theme.conf belongs to the package: editing it works until the next update
# silently reverts the login screen.
read -r -d '' THEME_CONF <<EOF
# Generated by install/sddm.sh — do not edit; edit the repo and re-run.
#
# Overrides $THEME_DIR/theme.conf without touching it, so a package
# update cannot revert this.
[General]
Font="Inter"
FontSize=11
ClockEnabled="true"
UserIcon="false"
# Show the last character briefly. Useful on a laptop keyboard in the dark,
# and no worse than the shoulder-surfing you already accept from a phone.
PasswordShowLastLetter=800
EOF

echo "==> Login screen"
note "theme       $SDDM_THEME_NAME   (from $THEME_LABEL)"
note "cursor      $CURSOR $CURSOR_SIZE"
note "writes      $CONF"
note "writes      $THEME_DIR/theme.conf.user"
echo

if ((DRY_RUN)); then
	echo "--- $CONF"
	printf '%s\n' "$MAIN_CONF"
	echo
	echo "--- $THEME_DIR/theme.conf.user"
	printf '%s\n' "$THEME_CONF"
	echo
	echo "Dry run — nothing written."
	exit 0
fi

command -v sudo >/dev/null 2>&1 || die "sudo not found."

echo "Both paths are root-owned, so this needs your password."
sudo install -d -m 755 "$CONF_DIR" || die "could not create $CONF_DIR"
printf '%s\n' "$MAIN_CONF" | sudo tee "$CONF" >/dev/null || die "could not write $CONF"
printf '%s\n' "$THEME_CONF" | sudo tee "$THEME_DIR/theme.conf.user" >/dev/null ||
	die "could not write $THEME_DIR/theme.conf.user"

echo
printf '\033[32mDone.\033[0m\n'
echo
echo "Preview it without logging out:"
echo
echo "    sddm-greeter-qt6 --test-mode --theme $THEME_DIR"
echo
echo "Less dangerous than it sounds: if a theme fails to load, SDDM logs the"
echo "error and falls back to its embedded theme rather than showing nothing"
echo "(GreeterApp.cpp, 'Fallback to embedded theme'). So a bad theme gives you"
echo "an ugly login screen, not an unusable one."
echo
echo "'systemctl restart sddm' applies it — and kills this session instantly."
echo "Save your work first. It also takes effect on the next reboot anyway."
