#!/usr/bin/env bash
# Install and configure the login screen.
#
#   ./install/sddm.sh              install the theme and point SDDM at it
#   ./install/sddm.sh --dry-run    print what would happen, touch nothing
#   ./install/sddm.sh --show       print the current SDDM config and exit
#
# The theme is ours: sddm/hypersetup/ in this repo. Blank background in the
# current palette, big centred clock, nothing else. No AUR package involved —
# an SDDM theme is just a directory with a Main.qml and a metadata.desktop.
#
# Why this is a separate script rather than part of set-theme.py or link.sh:
#
# SDDM is not part of your session. It runs as the `sddm` system user, on its
# own VT, BEFORE you log in — so it cannot read ~/.config, it is not affected
# by `hyprctl reload`, and it does not see anything link.sh symlinks. Its
# config lives in /etc/sddm.conf.d/ and its themes in /usr/share/sddm/themes/,
# both root-owned. Every other file in this repo is written without a
# password; this one is not.
#
# Consequence: the login screen does NOT follow SUPER+ALT+T. set-theme.py
# regenerates sddm/hypersetup/theme.conf, but getting that into /usr/share
# means re-running this.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

CONF_DIR="/etc/sddm.conf.d"
CONF="$CONF_DIR/10-hypersetup.conf"
THEME_ROOT="/usr/share/sddm/themes"
THEME_NAME="hypersetup"
THEME_SRC="$HERE/sddm/$THEME_NAME"
THEME_DIR="$THEME_ROOT/$THEME_NAME"

DRY_RUN=0
SHOW=0
for arg in "$@"; do
	case "$arg" in
	--dry-run) DRY_RUN=1 ;;
	--show) SHOW=1 ;;
	*)
		echo "unknown flag: $arg" >&2
		exit 1
		;;
	esac
done

die() {
	printf '\033[31mError:\033[0m %s\n' "$*" >&2
	exit 1
}
note() { printf '  %s\n' "$*"; }

if ((SHOW)); then
	echo "==> $CONF"
	if [[ -f $CONF ]]; then cat "$CONF"; else echo "  (not written yet)"; fi
	echo
	echo "==> installed themes in $THEME_ROOT"
	if [[ -d $THEME_ROOT ]]; then
		ls -1 "$THEME_ROOT" | sed 's/^/  /'
	else
		echo "  (no theme directory — is sddm installed?)"
	fi
	exit 0
fi

[[ -d $THEME_SRC ]] || die "$THEME_SRC not found."
[[ -f $THEME_SRC/Main.qml ]] || die "$THEME_SRC/Main.qml missing."
# Generated by set-theme.py. Without it every colour in Main.qml resolves to
# an empty string and the greeter comes up black on black.
[[ -f $THEME_SRC/theme.conf ]] ||
	die "$THEME_SRC/theme.conf missing — run ./install/set-theme.py <theme> first."

# Which theme the palette came from, for the summary line only.
THEME_LABEL="$(sed -n 's/^# Generated by .* from themes\/\(.*\)\.toml.*/\1/p' "$THEME_SRC/theme.conf" | head -1)"
THEME_LABEL="${THEME_LABEL:-unknown}"

# Font and cursor come from the desktop config so the login screen is not the
# one place with a different cursor. A stock X11 cursor over a themed greeter
# is the single most obvious "unthemed" tell.
CURSOR="$(sed -n 's/^export XCURSOR_THEME=//p' config/uwsm/env | head -1)"
CURSOR="${CURSOR:-Bibata-Modern-Classic}"
CURSOR_SIZE="$(sed -n 's/^export XCURSOR_SIZE=//p' config/uwsm/env | head -1)"
CURSOR_SIZE="${CURSOR_SIZE:-24}"

read -r -d '' MAIN_CONF <<EOF
# Generated by install/sddm.sh — do not edit; edit the repo and re-run.
#
# Drop-in, so it overrides /etc/sddm.conf without replacing it. Files in
# /etc/sddm.conf.d are read in alphabetical order; 10- puts this after
# anything a package ships as 00-.

[Theme]
Current=$THEME_NAME
CursorTheme=$CURSOR
CursorSize=$CURSOR_SIZE
# The theme draws no avatars, so this only stops SDDM loading them.
EnableAvatars=false

[General]
# Qt's automatic high-DPI scaling is already on by default for both display
# servers; left alone deliberately. If the greeter comes up too small on the
# 2560x1600 panel, the knob is GreeterEnvironment=QT_FONT_DPI=144 here. The
# clock scales with screen height on its own, so it is the fields and buttons
# that would look wrong, not the clock.
#
# DisplayServer is left at its default of x11. SDDM's own config source calls
# Wayland support experimental, and it needs a separate compositor
# (Wayland.CompositorCommand defaults to \`weston --shell=kiosk\`, which is not
# installed). Not worth risking the login screen for.
Numlock=on

[Users]
HideShells=/usr/bin/nologin,/sbin/nologin,/bin/false
EOF

echo "==> Login screen"
note "theme       $THEME_NAME  (palette from themes/$THEME_LABEL.toml)"
note "cursor      $CURSOR $CURSOR_SIZE"
note "installs    $THEME_SRC/  ->  $THEME_DIR/"
note "writes      $CONF"
echo

if ((DRY_RUN)); then
	echo "--- files that would be installed"
	find "$THEME_SRC" -type f | sed "s|^$THEME_SRC|  $THEME_DIR|"
	echo
	echo "--- $CONF"
	printf '%s\n' "$MAIN_CONF"
	echo
	echo "Dry run — nothing written."
	exit 0
fi

command -v sudo >/dev/null 2>&1 || die "sudo not found."
[[ -d $THEME_ROOT ]] || die "$THEME_ROOT does not exist — is sddm installed?"

echo "Both destinations are root-owned, so this needs your password."

# Copy rather than symlink. A symlink into $HOME would be followed by a
# process running as the `sddm` user, which cannot traverse a 700 home
# directory — the greeter would fail to load its own theme.
sudo rm -rf "$THEME_DIR" || die "could not clear $THEME_DIR"
sudo install -d -m 755 "$THEME_DIR" || die "could not create $THEME_DIR"
sudo cp -a "$THEME_SRC/." "$THEME_DIR/" || die "could not copy the theme"
sudo chmod -R a+rX "$THEME_DIR" || die "could not fix permissions on $THEME_DIR"

sudo install -d -m 755 "$CONF_DIR" || die "could not create $CONF_DIR"
printf '%s\n' "$MAIN_CONF" | sudo tee "$CONF" >/dev/null || die "could not write $CONF"

echo
printf '\033[32mDone.\033[0m\n'
echo
echo "Preview it without logging out:"
echo
echo "    sddm-greeter-qt6 --test-mode --theme $THEME_DIR"
echo
echo "Less dangerous than it sounds: if a theme fails to load, SDDM logs the"
echo "error and falls back to its embedded theme rather than showing nothing"
echo "(GreeterApp.cpp, 'Fallback to embedded theme'). So a broken theme gives"
echo "you an ugly login screen, not an unusable one."
echo
echo "'systemctl restart sddm' applies it — and kills this session instantly."
echo "Save your work first. It also takes effect on the next reboot anyway."
