#!/usr/bin/env python3
"""Render every config's colours from a single palette file.

    ./install/set-theme.py                 list available themes
    ./install/set-theme.py mocha           apply a theme
    ./install/set-theme.py --pick          choose one with rofi
    ./install/set-theme.py mocha --check   verify files are up to date (CI)

Colour used to live in thirteen files as 341 separate hex literals. This
generates all of it from themes/<name>.toml instead, so changing the accent
colour is one edit and one command.

Two mechanisms are used, depending on what each config format supports:

  * a generated file that the real config imports/includes/sources — used
    wherever the format has such a directive (CSS, kitty, rofi, fish,
    hyprlang). The hand-written config stays hand-written.
  * marked regions, replaced in place — used for formats with no import
    (TOML, JSONC). Everything between the >>> and <<< markers is generated;
    everything outside is yours.

Generated files carry a header saying so. Do not edit them; edit the theme.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEMES = ROOT / "themes"
CONFIG = ROOT / "config"

BANNER = "Generated by install/set-theme.py from themes/{name}.toml — do not edit."

REQUIRED_PALETTE = {
    "crust", "mantle", "base", "surface0", "surface1", "surface2",
    "overlay0", "overlay1", "overlay2", "subtext0", "subtext1", "text",
    "rosewater", "flamingo", "pink", "mauve", "red", "maroon", "peach",
    "yellow", "green", "teal", "sky", "sapphire", "blue", "lavender",
}
REQUIRED_ROLES = {"accent", "accent_alt", "urgent", "warning", "success", "info", "link"}
ANSI_ORDER = [
    "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
    "bright_black", "bright_red", "bright_green", "bright_yellow",
    "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
]


class Theme:
    def __init__(self, path: Path):
        self.path = path
        self.stem = path.stem
        with path.open("rb") as fh:
            raw = tomllib.load(fh)

        self.name = raw.get("name", self.stem)
        self.dark = raw.get("dark", True)
        self.gtk_theme = raw.get("gtk_theme", "")
        self.icon_theme = raw.get("icon_theme", "Papirus-Dark")
        self.palette: dict[str, str] = raw["palette"]
        self.roles: dict[str, str] = raw["roles"]
        self.ansi: dict[str, str] = raw.get("ansi", {})

        missing = REQUIRED_PALETTE - self.palette.keys()
        if missing:
            sys.exit(f"{path}: [palette] is missing: {', '.join(sorted(missing))}")
        missing = REQUIRED_ROLES - self.roles.keys()
        if missing:
            sys.exit(f"{path}: [roles] is missing: {', '.join(sorted(missing))}")
        for role, key in self.roles.items():
            if key not in self.palette:
                sys.exit(f"{path}: [roles].{role} points at unknown colour '{key}'")
        for slot, key in self.ansi.items():
            if key not in self.palette:
                sys.exit(f"{path}: [ansi].{slot} points at unknown colour '{key}'")
        for key, value in self.palette.items():
            if not (value.startswith("#") and len(value) == 7):
                sys.exit(f"{path}: {key} = {value!r} is not a #rrggbb colour")

    # -- lookups ---------------------------------------------------------

    def hex(self, key: str) -> str:
        """#rrggbb"""
        return self.palette[key]

    def bare(self, key: str) -> str:
        """rrggbb, no hash — kitty, fish and rofi all want this somewhere."""
        return self.palette[key].lstrip("#")

    def role(self, name: str) -> str:
        return self.palette[self.roles[name]]

    def role_bare(self, name: str) -> str:
        return self.role(name).lstrip("#")

    def ansi_hex(self, slot: str) -> str:
        return self.palette[self.ansi.get(slot, "text")]

    def argb(self, key: str, alpha: str = "ff") -> str:
        """#aarrggbb — Qt's palette format."""
        return f"#{alpha}{self.bare(key)}"

    def rgba(self, key: str, alpha: str = "ff") -> str:
        """rgba(rrggbbaa) — Hyprland and hyprlang tools."""
        return f"rgba({self.bare(key)}{alpha})"


# ---------------------------------------------------------------- writing


def write(path: Path, content: str, results: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        results.append(("same", path))
        return
    path.write_text(content, encoding="utf-8")
    results.append(("wrote", path))


def replace_marked(path: Path, block: str, comment: str, results: list) -> None:
    """Replace the region between >>> and <<< markers, leaving the rest alone."""
    start = f"{comment} >>> palette >>>"
    end = f"{comment} <<< palette <<<"

    text = path.read_text(encoding="utf-8")
    if start not in text or end not in text:
        sys.exit(
            f"{path}: missing palette markers.\n"
            f"  Add these two lines around the colour section:\n"
            f"    {start}\n    {end}"
        )

    head, _, rest = text.partition(start)
    _, _, tail = rest.partition(end)
    new = f"{head}{start}\n{block.rstrip()}\n{end}{tail}"

    if new == text:
        results.append(("same", path))
        return
    path.write_text(new, encoding="utf-8")
    results.append(("wrote", path))


# --------------------------------------------------------------- emitters


def gen_hypr_theme_lua(t: Theme) -> str:
    lines = [
        f"-- {BANNER.format(name=t.stem)}",
        "--",
        f"-- Theme: {t.name}",
        "--",
        "-- Hyprland accepts colours as \"rgb(rrggbb)\" or \"rgba(rrggbbaa)\".",
        "-- The `_a` variants are semi-transparent, for borders and shadows.",
        "",
        "return {",
    ]
    for key in sorted(t.palette):
        lines.append(f'  {key:<10}= "rgb({t.bare(key)})",')
    lines.append("")
    lines.append("  -- Semantic roles — what a colour *means*, not what it is.")
    for role in sorted(t.roles):
        lines.append(f'  {role:<10}= "rgb({t.role_bare(role)})",')
    lines.append("")
    lines.append("  -- Semi-transparent, for gradients and shadows.")
    lines.append(f'  accent_a  = "{t.rgba(t.roles["accent"], "ee")}",')
    lines.append(f'  accent2_a = "{t.rgba(t.roles["accent_alt"], "ee")}",')
    lines.append(f'  surface_a = "{t.rgba("surface1", "aa")}",')
    lines.append(f'  shadow    = "{t.rgba("crust", "ee")}",')
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_hypr_colors_conf(t: Theme) -> str:
    """hyprlang variables, sourced by hyprlock.conf."""
    lines = [f"# {BANNER.format(name=t.stem)}", "", f"# Theme: {t.name}", ""]
    for key in sorted(t.palette):
        lines.append(f"${key} = {t.rgba(key)}")
    lines.append("")
    for role in sorted(t.roles):
        lines.append(f"${role} = {t.rgba(t.roles[role])}")
    lines.append("")
    lines.append("# Translucent variants, for lock-screen fills and shadows.")
    lines.append(f"$base_a   = {t.rgba('base', 'cc')}")
    lines.append(f"$crust_a  = {t.rgba('crust', '99')}")
    lines.append(f"$accent_a = {t.rgba(t.roles['accent'], 'ee')}")
    lines.append(f"$accent2_a = {t.rgba(t.roles['accent_alt'], 'ee')}")
    lines.append(f"$urgent_a = {t.rgba(t.roles['urgent'], 'ee')}")
    lines.append(f"$warning_a = {t.rgba(t.roles['warning'], 'ee')}")
    return "\n".join(lines) + "\n"


def gen_css_colors(t: Theme) -> str:
    lines = [f"/* {BANNER.format(name=t.stem)} */", f"/* Theme: {t.name} */", ""]
    for key in sorted(t.palette):
        lines.append(f"@define-color {key} {t.hex(key)};")
    lines.append("")
    for role in sorted(t.roles):
        lines.append(f"@define-color {role} {t.role(role)};")
    return "\n".join(lines) + "\n"


def gen_kitty_colors(t: Theme) -> str:
    lines = [
        f"# {BANNER.format(name=t.stem)}",
        f"# Theme: {t.name}",
        "",
        f"foreground            {t.hex('text')}",
        f"background            {t.hex('base')}",
        f"selection_foreground  {t.hex('base')}",
        f"selection_background  {t.hex('rosewater')}",
        "",
        f"cursor                {t.hex('rosewater')}",
        f"cursor_text_color     {t.hex('base')}",
        f"url_color             {t.role('link')}",
        "",
        f"active_border_color   {t.role('accent')}",
        f"inactive_border_color {t.hex('overlay0')}",
        f"bell_border_color     {t.role('warning')}",
        "",
        f"active_tab_foreground   {t.hex('crust')}",
        f"active_tab_background   {t.role('accent')}",
        f"inactive_tab_foreground {t.hex('text')}",
        f"inactive_tab_background {t.hex('mantle')}",
        f"tab_bar_background      {t.hex('crust')}",
        "",
        "# The 16 ANSI colours, from [ansi] in the theme file.",
    ]
    for i, slot in enumerate(ANSI_ORDER):
        lines.append(f"color{i:<2} {t.ansi_hex(slot)}")
    return "\n".join(lines) + "\n"


def gen_rofi_colors(t: Theme) -> str:
    lines = [
        f"// {BANNER.format(name=t.stem)}",
        f"// Theme: {t.name}",
        "",
        "* {",
    ]
    for key in sorted(t.palette):
        lines.append(f"  {key + ':':<12}{t.hex(key)};")
    lines.append("")
    for role in sorted(t.roles):
        lines.append(f"  {role.replace('_', '-') + ':':<12}{t.role(role)};")
    lines.append("")
    lines.append("  /* Shorthands used by the theme files. */")
    lines.append(f"  bg:         {t.hex('base')};")
    lines.append(f"  bg-alt:     {t.hex('mantle')};")
    lines.append(f"  bg-dim:     {t.hex('crust')};")
    lines.append(f"  fg:         {t.hex('text')};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_fish_colors(t: Theme) -> str:
    """fish wants bare hex, no leading #."""
    lines = [
        f"# {BANNER.format(name=t.stem)}",
        f"# Theme: {t.name}",
        "",
        "# Syntax highlighting",
        f"set -g fish_color_normal          {t.bare('text')}",
        f"set -g fish_color_command         {t.role_bare('accent_alt')}",
        f"set -g fish_color_keyword         {t.bare('red')}",
        f"set -g fish_color_quote           {t.bare('green')}",
        f"set -g fish_color_redirection     {t.bare('pink')}",
        f"set -g fish_color_end             {t.bare('peach')}",
        f"set -g fish_color_error           {t.role_bare('urgent')}",
        f"set -g fish_color_param           {t.bare('text')}",
        f"set -g fish_color_comment         {t.bare('overlay0')}",
        f"set -g fish_color_operator        {t.bare('pink')}",
        f"set -g fish_color_escape          {t.bare('maroon')}",
        f"set -g fish_color_autosuggestion  {t.bare('overlay0')}",
        f"set -g fish_color_selection       --background={t.bare('surface1')}",
        f"set -g fish_color_search_match    --background={t.bare('surface1')}",
        "",
        "# Completion pager",
        f"set -g fish_pager_color_progress    {t.bare('overlay0')}",
        f"set -g fish_pager_color_prefix      {t.bare('pink')}",
        f"set -g fish_pager_color_completion  {t.bare('text')}",
        f"set -g fish_pager_color_description {t.bare('overlay0')}",
        f"set -g fish_pager_color_selected_background --background={t.bare('surface1')}",
    ]
    return "\n".join(lines) + "\n"


def gen_gtk4_css(t: Theme) -> str:
    """libadwaita ignores gtk-theme-name; overriding its named colours is the
    only supported way to restyle GTK4 apps."""
    fg_on_accent = t.hex("crust") if t.dark else t.hex("base")
    lines = [
        f"/* {BANNER.format(name=t.stem)} */",
        f"/* Theme: {t.name} */",
        "/*",
        " * GTK4 / libadwaita apps deliberately ignore gtk-theme-name. Overriding",
        " * libadwaita's named colours here is the supported way to theme them.",
        " */",
        "",
    ]
    pairs = [
        ("accent_color", t.role("accent")),
        ("accent_bg_color", t.role("accent")),
        ("accent_fg_color", fg_on_accent),
        ("destructive_color", t.role("urgent")),
        ("destructive_bg_color", t.role("urgent")),
        ("destructive_fg_color", fg_on_accent),
        ("success_color", t.role("success")),
        ("success_bg_color", t.role("success")),
        ("success_fg_color", fg_on_accent),
        ("warning_color", t.role("warning")),
        ("warning_bg_color", t.role("warning")),
        ("warning_fg_color", fg_on_accent),
        ("error_color", t.role("urgent")),
        ("error_bg_color", t.role("urgent")),
        ("error_fg_color", fg_on_accent),
        ("window_bg_color", t.hex("base")),
        ("window_fg_color", t.hex("text")),
        ("view_bg_color", t.hex("base")),
        ("view_fg_color", t.hex("text")),
        ("headerbar_bg_color", t.hex("mantle")),
        ("headerbar_fg_color", t.hex("text")),
        ("headerbar_border_color", t.hex("surface1")),
        ("headerbar_backdrop_color", t.hex("base")),
        ("card_bg_color", t.hex("surface0")),
        ("card_fg_color", t.hex("text")),
        ("dialog_bg_color", t.hex("base")),
        ("dialog_fg_color", t.hex("text")),
        ("popover_bg_color", t.hex("mantle")),
        ("popover_fg_color", t.hex("text")),
        ("sidebar_bg_color", t.hex("mantle")),
        ("sidebar_fg_color", t.hex("text")),
        ("sidebar_backdrop_color", t.hex("crust")),
        ("sidebar_border_color", t.hex("surface1")),
        ("thumbnail_bg_color", t.hex("surface0")),
        ("thumbnail_fg_color", t.hex("text")),
        ("scrollbar_outline_color", t.hex("surface1")),
    ]
    for name, value in pairs:
        lines.append(f"@define-color {name:<26}{value};")
    lines.append("")
    lines.append("@define-color shade_color          rgba(0, 0, 0, 0.36);")
    lines.append("@define-color card_shade_color     rgba(0, 0, 0, 0.36);")
    lines.append("@define-color headerbar_shade_color rgba(0, 0, 0, 0.36);")
    lines.append("@define-color sidebar_shade_color  rgba(0, 0, 0, 0.36);")
    return "\n".join(lines) + "\n"


def gen_qt_palette(t: Theme) -> str:
    """qt6ct/qt5ct colour scheme: 21 roles per state, #aarrggbb."""

    def row(*keys_or_roles: str) -> str:
        out = []
        for k in keys_or_roles:
            out.append(k if k.startswith("#") else t.argb(k))
        return ", ".join(out)

    active = row(
        "text", "surface0", "surface2", "surface1", "crust", "surface0",
        "text", t.role("urgent").replace("#", "#ff"), "text", "base", "base",
        "crust", t.role("accent").replace("#", "#ff"), "crust",
        t.role("link").replace("#", "#ff"), t.role("accent").replace("#", "#ff"),
        "mantle", "base", "surface0", "text", "overlay0",
    )
    inactive = row(
        "text", "surface0", "surface2", "surface1", "crust", "surface0",
        "text", t.role("urgent").replace("#", "#ff"), "text", "base", "base",
        "crust", "surface2", "text",
        t.role("link").replace("#", "#ff"), t.role("accent").replace("#", "#ff"),
        "mantle", "base", "surface0", "text", "overlay0",
    )
    disabled = row(
        "overlay0", "surface0", "surface2", "surface1", "crust", "surface0",
        "overlay0", t.role("urgent").replace("#", "#ff"), "overlay0", "mantle",
        "base", "crust", "surface1", "overlay0", "overlay0", "overlay0",
        "mantle", "base", "surface0", "overlay0", "surface1",
    )
    return "\n".join([
        "[ColorScheme]",
        f"; {BANNER.format(name=t.stem)}",
        f"; Theme: {t.name}",
        ";",
        "; Role order: WindowText, Button, Light, Midlight, Dark, Mid, Text,",
        "; BrightText, ButtonText, Base, Window, Shadow, Highlight,",
        "; HighlightedText, Link, LinkVisited, AlternateBase, NoRole,",
        "; ToolTipBase, ToolTipText, PlaceholderText",
        "",
        f"active_colors={active}",
        f"inactive_colors={inactive}",
        f"disabled_colors={disabled}",
    ]) + "\n"


def gen_starship_palette(t: Theme) -> str:
    lines = [f'[palettes.desktop]']
    for key in sorted(t.palette):
        lines.append(f'{key} = "{t.hex(key)}"')
    for role in sorted(t.roles):
        lines.append(f'{role} = "{t.role(role)}"')
    return "\n".join(lines)


def gen_waybar_calendar(t: Theme) -> str:
    return "\n".join([
        '      "format": {',
        f'        "months":   "<span color=\'{t.role("accent")}\'><b>{{}}</b></span>",',
        f'        "days":     "<span color=\'{t.hex("text")}\'>{{}}</span>",',
        f'        "weeks":    "<span color=\'{t.hex("overlay0")}\'>W{{}}</span>",',
        f'        "weekdays": "<span color=\'{t.hex("overlay1")}\'><b>{{}}</b></span>",',
        f'        "today":    "<span color=\'{t.role("accent")}\'><b><u>{{}}</u></b></span>"',
        '      }',
    ])


def gen_gtk3_theme(t: Theme) -> str:
    return "\n".join([
        f"gtk-theme-name={t.gtk_theme}",
        f"gtk-icon-theme-name={t.icon_theme}",
    ])


# ------------------------------------------------------------------- main


def apply(t: Theme, check: bool) -> int:
    results: list = []

    write(CONFIG / "hypr/conf/theme.lua", gen_hypr_theme_lua(t), results)
    write(CONFIG / "hypr/colors.conf", gen_hypr_colors_conf(t), results)
    write(CONFIG / "waybar/colors.css", gen_css_colors(t), results)
    write(CONFIG / "swaync/colors.css", gen_css_colors(t), results)
    write(CONFIG / "kitty/colors.conf", gen_kitty_colors(t), results)
    write(CONFIG / "rofi/colors.rasi", gen_rofi_colors(t), results)
    write(CONFIG / "fish/colors.fish", gen_fish_colors(t), results)
    write(CONFIG / "gtk-4.0/gtk.css", gen_gtk4_css(t), results)
    write(CONFIG / "qt6ct/colors/palette.conf", gen_qt_palette(t), results)
    write(CONFIG / "qt5ct/colors/palette.conf", gen_qt_palette(t), results)

    replace_marked(CONFIG / "starship.toml", gen_starship_palette(t), "#", results)
    replace_marked(CONFIG / "waybar/config.jsonc", gen_waybar_calendar(t), "//", results)
    replace_marked(CONFIG / "gtk-3.0/settings.ini", gen_gtk3_theme(t), "#", results)

    # Record which theme is live, so scripts and prompts can ask.
    state = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state")) / "hypr"
    if not check:
        state.mkdir(parents=True, exist_ok=True)
        (state / "theme").write_text(t.stem + "\n", encoding="utf-8")

    changed = [p for status, p in results if status == "wrote"]

    if check:
        if changed:
            print(f"Out of date with themes/{t.stem}.toml:")
            for p in changed:
                print(f"  {p.relative_to(ROOT)}")
            print("\nRun: ./install/set-theme.py " + t.stem)
            return 1
        print(f"All colour files match themes/{t.stem}.toml")
        return 0

    print(f"Applied {t.name} ({t.stem})")
    for status, p in results:
        mark = "\033[32mwrote\033[0m" if status == "wrote" else "unchanged"
        print(f"  {mark:<18} {p.relative_to(ROOT)}")

    if changed:
        print(
            "\nReload the live session with:\n"
            "  hyprctl reload\n"
            "  pkill waybar; waybar & disown\n"
            "  swaync-client -rs\n"
            "  kill -SIGUSR1 $(pgrep kitty)      # kitty re-reads its config\n"
            "  ~/.config/hypr/scripts/theme.sh   # GTK theme name + gsettings\n"
        )
    return 0


def list_themes() -> list[Path]:
    return sorted(THEMES.glob("*.toml"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("theme", nargs="?", help="theme name (file stem in themes/)")
    ap.add_argument("--pick", action="store_true", help="choose with rofi")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any file is out of date")
    args = ap.parse_args()

    available = list_themes()
    if not available:
        sys.exit(f"No themes in {THEMES}")

    name = args.theme

    if args.pick:
        menu = "\n".join(p.stem for p in available)
        try:
            proc = subprocess.run(
                ["rofi", "-dmenu", "-i", "-p", "Theme", "-no-custom",
                 "-theme", "powermenu"],
                input=menu, capture_output=True, text=True, check=False,
            )
        except FileNotFoundError:
            sys.exit("rofi is not installed")
        name = proc.stdout.strip()
        if not name:
            return 0

    if not name:
        print("Available themes:\n")
        current = None
        state = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state"))
        marker = state / "hypr/theme"
        if marker.exists():
            current = marker.read_text(encoding="utf-8").strip()
        for p in available:
            t = Theme(p)
            flag = "  <- current" if p.stem == current else ""
            print(f"  {p.stem:<12} {t.name}{flag}")
        print("\nApply one:  ./install/set-theme.py <name>")
        return 0

    path = THEMES / f"{name}.toml"
    if not path.exists():
        sys.exit(f"No such theme: {name}\nAvailable: "
                 + ", ".join(p.stem for p in available))

    return apply(Theme(path), args.check)


if __name__ == "__main__":
    sys.exit(main())
